receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      filesystem:
        metrics:
          system.filesystem.usage: {}
      disk:
        metrics:
          system.disk.io: {}
  
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
    send_batch_max_size: 2048
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
    spike_limit_mib: 512

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: machine_logger
    const_labels:
      service: "disk_monitor"
  
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]
